### ISSUE TITLE
Unable to load extension : error message

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/chrome-extension#23]
@hassan3kb, @richagarg278 our designer is not able to install the chrome extension. 
Here is the errors she encounters: 

1/ you can see error in the marketplace/where extensions are installed
![image](https://github.com/jupyter-naas/naas-chrome-extension/assets/21052349/d4826fd5-09aa-4f8c-a0b5-f94bb6a48686)

2/ you can see the "service worker registration failed" 
![image](https://github.com/jupyter-naas/naas-chrome-extension/assets/21052349/6f2f23f3-dd9c-49a6-97f7-a64b5d497e35)

3/ you can see the "uncaught TypeError" message
![image](https://github.com/jupyter-naas/naas-chrome-extension/assets/21052349/e4f3b78d-f096-4a24-bebc-8ce62ee2dd47)

**Comment by Dr0p42** [comment]
Fixed
