### ISSUE TITLE
Re build and deploy the extension

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/chrome-extension#27]
Tasks:
- Removal of the tabs : Search/Chat/Dashboard/Extension, we should have the same experience as the mobile application. 
- Change of the name to "NaasAI" vs long name we currently have "[Naas: AI Assistant for Analytics & Automation](https://chromewebstore.google.com/detail/cpkgfedlkfiknjpkmhcglmjiefnechpp)"
- Rebuild/push to Chrome store

**Comment by jravenel** [comment]
@Dr0p42 can you sync with @hassan3kb to share credentials to him so he can push autonomously?

**Comment by hassan3kb** [comment]
The updated extension has been published.
